/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package grupo7.struts.action;

import grupo7.struts.form.LoginForm;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 04-21-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="exitoLogin" path="/Ifaz_root.jsp"
 *                        redirect="true"
 * @struts.action-forward name="falloLogin" path="/login.jsp" redirect="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;
		PruebaDataBase testDB = new PruebaDataBase();

		if (loginForm.getTxtUsuario().equals("root")
				&& loginForm.getPwdClave().equals("root")) {
			try {
				if (testDB.conectar())return mapping.findForward("exitoLoginRoot");
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		return mapping.findForward("falloLogin");

	}
}