/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package grupo7.struts.action;

import java.sql.DriverManager;
import java.sql.SQLException;



public class PruebaDataBase {
	public boolean conectar() throws Exception {

		java.sql.Connection myConnection = null;
		try {
			Class.forName("com.mysql.jdbc.Driver").newInstance();
			myConnection = DriverManager.getConnection(
					"jdbc:mysql://localhost:3306/eev", "si3_grupo7", "si3");
			if (myConnection != null) {
				System.out.println("la conexion ha sido correcta");
				return true;
			}

			// do what you wish with myConnection
		} catch (SQLException sqle) {
			System.out.println(sqle);
		} finally {
			// enclose this in a finally block to make
			// sure the connection is closed
			myConnection.close();
			try {
				myConnection.close();
			} catch (SQLException e) {
				System.out.println(e);
			}
		}
		return false;

	}
}